// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from hello.djinni

#include "NativeHello.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeHello::NativeHello() : ::djinni::JniInterface<::netvirta::Hello, NativeHello>("com/netvirta/testgles/generated/Hello$CppProxy") {}

NativeHello::~NativeHello() = default;


CJNIEXPORT void JNICALL Java_com_netvirta_testgles_generated_Hello_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::netvirta::Hello>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_netvirta_testgles_generated_Hello_create(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::netvirta::Hello::create();
        return ::djinni::release(::djinni_generated::NativeHello::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jstring JNICALL Java_com_netvirta_testgles_generated_Hello_00024CppProxy_native_1setString(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_text)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::netvirta::Hello>(nativeRef);
        auto r = ref->setString(::djinni::String::toCpp(jniEnv, j_text));
        return ::djinni::release(::djinni::String::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
