// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni

// HelloWorld_Bridging_Header.h
// HelloWorld_Bridging_Header

#import <Foundation/Foundation.h>

//! Project version number for HelloWorldBridgingHeader.
FOUNDATION_EXPORT double HelloWorldBridgingHeaderVersionNumber;

//! Project version string for HelloWorldBridgingHeader.
FOUNDATION_EXPORT const unsigned char HelloWorldBridgingHeaderVersionString[];

#import "NVHello.h"
