// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from hello.djinni

#import <Foundation/Foundation.h>
@class NVHello;


@interface NVHello : NSObject

+ (nullable NVHello *)create;

- (nonnull NSString *)setString:(nonnull NSString *)text;

@end
