// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from hello.djinni

#pragma once

#include <memory>
#include <string>

namespace netvirta {

class Hello {
public:
    virtual ~Hello() {}

    static std::shared_ptr<Hello> create();

    virtual std::string setString(const std::string & text) = 0;
};

}  // namespace netvirta
