// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from hello.djinni

#include "Hello.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NVHello;

namespace djinni_generated {

class Hello
{
public:
    using CppType = std::shared_ptr<::netvirta::Hello>;
    using CppOptType = std::shared_ptr<::netvirta::Hello>;
    using ObjcType = NVHello*;

    using Boxed = Hello;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

