// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from hello.djinni

#import "NVHello+Private.h"
#import "NVHello.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface NVHello ()

- (id)initWithCpp:(const std::shared_ptr<::netvirta::Hello>&)cppRef;

@end

@implementation NVHello {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::netvirta::Hello>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::netvirta::Hello>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable NVHello *)create {
    try {
        auto objcpp_result_ = ::netvirta::Hello::create();
        return ::djinni_generated::Hello::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)setString:(nonnull NSString *)text {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->setString(::djinni::String::toCpp(text));
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto Hello::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto Hello::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<NVHello>(cpp);
}

}  // namespace djinni_generated

@end
